import { EcclesiasticalRank } from '@/types';

export const ESOCS_RANKS: EcclesiasticalRank[] = [
  // ==========================================
  // --- MALE ORDER OF ORDINATION (12 RANKS) ---
  // ==========================================
  {
    id: 'rank_brother',
    name: 'Brother',
    shortCode: 'BRO',
    orderLevel: 0,
    genderEligibility: 'male',
    minimumYearsInCurrentRank: 1,
    robingCategory: 'White_Gold',
    liturgicalColor: 'White',
    badgeColor: 'bg-slate-100 text-slate-800 border-slate-300 dark:bg-slate-800 dark:text-slate-200',
    theologicalRequirements: ['Baptismal Catechism', 'Order of Holy Services & C&S Doctrine'],
    description: 'Baptized faithful brother of the Holy Order.',
    levyBreakdown: {
      branchLevy: 5000,
      districtLevy: 5000,
      provincialLevy: 5000,
      nationalFee: 10000,
      total: 25000,
    },
  },
  {
    id: 'rank_aladura_male',
    name: 'Aladura',
    shortCode: 'ALD',
    orderLevel: 1,
    genderEligibility: 'male',
    prerequisiteRankId: 'rank_brother',
    prerequisiteRankName: 'Brother',
    minimumYearsInCurrentRank: 2,
    robingCategory: 'White_Gold',
    liturgicalColor: 'White',
    badgeColor: 'bg-slate-100 text-slate-800 border-slate-300 dark:bg-slate-800 dark:text-slate-200',
    theologicalRequirements: ['Basic Liturgy 101', 'Foundations of Prayer & Altar Sanctification'],
    description: 'Foundational holy order of prayer, intercession, and sanctuary preparation.',
    levyBreakdown: {
      branchLevy: 7000,
      districtLevy: 7000,
      provincialLevy: 8000,
      nationalFee: 13000,
      total: 35000,
    },
  },
  {
    id: 'rank_leader_male',
    name: 'Leader',
    shortCode: 'LDR',
    orderLevel: 2,
    genderEligibility: 'male',
    prerequisiteRankId: 'rank_aladura_male',
    prerequisiteRankName: 'Aladura',
    minimumYearsInCurrentRank: 2,
    robingCategory: 'White_Gold',
    liturgicalColor: 'White',
    badgeColor: 'bg-slate-100 text-slate-800 border-slate-300 dark:bg-slate-800 dark:text-slate-200',
    theologicalRequirements: ['Leadership in the Sanctuary', 'Order of Divine Services', 'Pastoral Stewardship'],
    description: 'Parish leader assisting elders in conducting services and pastoral coordination.',
    levyBreakdown: {
      branchLevy: 9000,
      districtLevy: 9000,
      provincialLevy: 12000,
      nationalFee: 15000,
      total: 45000,
    },
  },
  {
    id: 'rank_rabbi',
    name: 'Rabbi',
    shortCode: 'RAB',
    orderLevel: 3,
    genderEligibility: 'male',
    prerequisiteRankId: 'rank_leader_male',
    prerequisiteRankName: 'Leader',
    minimumYearsInCurrentRank: 3,
    robingCategory: 'White_Gold',
    liturgicalColor: 'White',
    badgeColor: 'bg-slate-100 text-slate-800 border-slate-300 dark:bg-slate-800 dark:text-slate-200',
    theologicalRequirements: ['Biblical Hermeneutics', 'Teacher in Israel Colloquium', 'Spiritual Warfare in Scripture'],
    description: 'Teachers and instructors of biblical doctrine, catechism, and sacred liturgical traditions.',
    levyBreakdown: {
      branchLevy: 10000,
      districtLevy: 10000,
      provincialLevy: 15000,
      nationalFee: 20000,
      total: 55000,
    },
  },
  {
    id: 'rank_pastor',
    name: 'Pastor',
    shortCode: 'PST',
    orderLevel: 4,
    genderEligibility: 'male',
    prerequisiteRankId: 'rank_rabbi',
    prerequisiteRankName: 'Rabbi',
    minimumYearsInCurrentRank: 3,
    robingCategory: 'White_Gold',
    liturgicalColor: 'White',
    badgeColor: 'bg-amber-100 text-amber-900 border-amber-300 dark:bg-amber-950/60 dark:text-amber-200',
    theologicalRequirements: ['Pastoral Care & Homiletics', 'Ecclesiastical Counseling', 'Parish Administration'],
    description: 'Shepherds of the local flock, preaching the Word and guiding parish members.',
    levyBreakdown: {
      branchLevy: 12000,
      districtLevy: 12000,
      provincialLevy: 18000,
      nationalFee: 23000,
      total: 65000,
    },
  },
  {
    id: 'rank_evangelist',
    name: 'Evangelist',
    shortCode: 'EVG',
    orderLevel: 5,
    genderEligibility: 'male',
    prerequisiteRankId: 'rank_pastor',
    prerequisiteRankName: 'Pastor',
    minimumYearsInCurrentRank: 3,
    robingCategory: 'White_Gold',
    liturgicalColor: 'White',
    badgeColor: 'bg-amber-100 text-amber-900 border-amber-300 dark:bg-amber-950/60 dark:text-amber-200',
    theologicalRequirements: ['Great Commission & Missions', 'Revival Ministry', 'Apologetics & Outreach'],
    description: 'Proclaimers of the Holy Gospel, revivalists, and missionary pioneers.',
    levyBreakdown: {
      branchLevy: 15000,
      districtLevy: 15000,
      provincialLevy: 20000,
      nationalFee: 30000,
      total: 80000,
    },
  },
  {
    id: 'rank_apostle_white',
    name: 'Apostle (White)',
    shortCode: 'APO',
    orderLevel: 6,
    genderEligibility: 'male',
    prerequisiteRankId: 'rank_evangelist',
    prerequisiteRankName: 'Evangelist',
    minimumYearsInCurrentRank: 4,
    robingCategory: 'White',
    liturgicalColor: 'White',
    badgeColor: 'bg-slate-100 text-slate-900 border-slate-400 font-bold dark:bg-slate-800 dark:text-white',
    theologicalRequirements: ['Advanced Ecclesiology', 'Church Administration', 'Liturgical Governance'],
    description: 'Foundational apostolic pillar with White liturgical stole, supervisory authority over divine services.',
    levyBreakdown: {
      branchLevy: 18000,
      districtLevy: 18000,
      provincialLevy: 24000,
      nationalFee: 35000,
      total: 95000,
    },
  },
  {
    id: 'rank_super_apostle_pink',
    name: 'Super Apostle (Pink)',
    shortCode: 'SUA',
    orderLevel: 7,
    genderEligibility: 'male',
    prerequisiteRankId: 'rank_apostle_white',
    prerequisiteRankName: 'Apostle (White)',
    minimumYearsInCurrentRank: 4,
    robingCategory: 'Pink',
    liturgicalColor: 'Pink',
    badgeColor: 'bg-pink-100 text-pink-900 border-pink-300 dark:bg-pink-950/60 dark:text-pink-200 font-bold',
    theologicalRequirements: ['Apostolic Jurisdiction & Council Laws', 'Synodical Liturgy', 'District Supervisory Ethics'],
    description: 'Super Apostle distinguished by Pink ceremonial liturgical sash, overseeing zonal parish developments.',
    levyBreakdown: {
      branchLevy: 20000,
      districtLevy: 20000,
      provincialLevy: 30000,
      nationalFee: 45000,
      total: 115000,
    },
  },
  {
    id: 'rank_senior_apostle_yellow',
    name: 'Senior Apostle (Yellow)',
    shortCode: 'SAP',
    orderLevel: 8,
    genderEligibility: 'male',
    prerequisiteRankId: 'rank_super_apostle_pink',
    prerequisiteRankName: 'Super Apostle (Pink)',
    minimumYearsInCurrentRank: 4,
    robingCategory: 'Yellow',
    liturgicalColor: 'Yellow',
    badgeColor: 'bg-yellow-100 text-yellow-900 border-yellow-400 dark:bg-yellow-950/60 dark:text-yellow-200 font-bold',
    theologicalRequirements: ['Synodical Jurisprudence', 'District Oversight & Episcopal Guidance', 'Theology of Sacraments'],
    description: 'Senior Apostle bearing Yellow/Gold bishopric stole, leading district governance and spiritual arbitration.',
    levyBreakdown: {
      branchLevy: 25000,
      districtLevy: 25000,
      provincialLevy: 35000,
      nationalFee: 55000,
      total: 140000,
    },
  },
  {
    id: 'rank_special_senior_apostle_blue',
    name: 'Special Senior Apostle (Blue)',
    shortCode: 'SSA',
    orderLevel: 9,
    genderEligibility: 'male',
    prerequisiteRankId: 'rank_senior_apostle_yellow',
    prerequisiteRankName: 'Senior Apostle (Yellow)',
    minimumYearsInCurrentRank: 5,
    robingCategory: 'Blue',
    liturgicalColor: 'Blue',
    badgeColor: 'bg-blue-100 text-blue-900 border-blue-400 dark:bg-blue-950/60 dark:text-blue-200 font-bold',
    theologicalRequirements: ['Provincial Leadership Colloquium', 'High Council Ethics & Governance', 'Constitutional Law of Holy Order'],
    description: 'Special Senior Apostle bearing Royal Blue velvet stole & gold trim, presiding over provincial dioceses and synod meetings.',
    levyBreakdown: {
      branchLevy: 30000,
      districtLevy: 30000,
      provincialLevy: 45000,
      nationalFee: 65000,
      total: 170000,
    },
  },
  {
    id: 'rank_apostle_general_green',
    name: 'Apostle General (Green)',
    shortCode: 'APG',
    orderLevel: 10,
    genderEligibility: 'male',
    prerequisiteRankId: 'rank_special_senior_apostle_blue',
    prerequisiteRankName: 'Special Senior Apostle (Blue)',
    minimumYearsInCurrentRank: 5,
    robingCategory: 'Green',
    liturgicalColor: 'Green',
    badgeColor: 'bg-emerald-100 text-emerald-900 border-emerald-400 dark:bg-emerald-950/60 dark:text-emerald-200 font-bold',
    theologicalRequirements: ['Apex Spiritual Council Fellowship', 'Holy Synod Supreme Ordinances', 'International Mission Jurisprudence'],
    description: 'Apostle General adorned in Emerald Green apex regalia, supreme council member advising His Most Eminence.',
    levyBreakdown: {
      branchLevy: 35000,
      districtLevy: 35000,
      provincialLevy: 50000,
      nationalFee: 80000,
      total: 200000,
    },
  },
  {
    id: 'rank_supervising_apostle_general_green',
    name: 'Supervising Apostle General (Green)',
    shortCode: 'SAG',
    orderLevel: 11,
    genderEligibility: 'male',
    prerequisiteRankId: 'rank_apostle_general_green',
    prerequisiteRankName: 'Apostle General (Green)',
    minimumYearsInCurrentRank: 6,
    robingCategory: 'Green',
    liturgicalColor: 'Green',
    badgeColor: 'bg-emerald-200 text-emerald-950 border-emerald-500 dark:bg-emerald-900/90 dark:text-emerald-100 font-extrabold shadow-sm',
    theologicalRequirements: ['Supreme Head Advisory Conclave', 'Apex Sovereign Ecclesiastical Doctorate', 'Universal Synod Presidency'],
    description: 'Supervising Apostle General bearing Emerald Green apex patriarchal regalia with gold fringe, commanding international diocesan oversight.',
    levyBreakdown: {
      branchLevy: 45000,
      districtLevy: 45000,
      provincialLevy: 60000,
      nationalFee: 100000,
      total: 250000,
    },
  },

  // ============================================
  // --- FEMALE ORDER OF ORDINATION (10 RANKS) ---
  // ============================================
  {
    id: 'rank_sister',
    name: 'Sister',
    shortCode: 'SIS',
    orderLevel: 0,
    genderEligibility: 'female',
    minimumYearsInCurrentRank: 1,
    robingCategory: 'White_Gold',
    liturgicalColor: 'White',
    badgeColor: 'bg-slate-100 text-slate-800 border-slate-300 dark:bg-slate-800 dark:text-slate-200',
    theologicalRequirements: ['Baptismal Catechism', 'Order of Holy Services & Sisterhood Devotion'],
    description: 'Baptized faithful sister of the Holy Order.',
    levyBreakdown: {
      branchLevy: 5000,
      districtLevy: 5000,
      provincialLevy: 5000,
      nationalFee: 10000,
      total: 25000,
    },
  },
  {
    id: 'rank_lady_aladura',
    name: 'Lady Aladura',
    shortCode: 'LAD',
    orderLevel: 1,
    genderEligibility: 'female',
    prerequisiteRankId: 'rank_sister',
    prerequisiteRankName: 'Sister',
    minimumYearsInCurrentRank: 2,
    robingCategory: 'White_Gold',
    liturgicalColor: 'White',
    badgeColor: 'bg-slate-100 text-slate-800 border-slate-300 dark:bg-slate-800 dark:text-slate-200',
    theologicalRequirements: ['Basic Liturgy 101', 'Foundations of Prayer & Altar Sanctification'],
    description: 'Foundational female order of prayer, intercession, and sanctuary preparation.',
    levyBreakdown: {
      branchLevy: 7000,
      districtLevy: 7000,
      provincialLevy: 8000,
      nationalFee: 13000,
      total: 35000,
    },
  },
  {
    id: 'rank_lady_leader',
    name: 'Lady Leader',
    shortCode: 'LLD',
    orderLevel: 2,
    genderEligibility: 'female',
    prerequisiteRankId: 'rank_lady_aladura',
    prerequisiteRankName: 'Lady Aladura',
    minimumYearsInCurrentRank: 2,
    robingCategory: 'White_Gold',
    liturgicalColor: 'White',
    badgeColor: 'bg-slate-100 text-slate-800 border-slate-300 dark:bg-slate-800 dark:text-slate-200',
    theologicalRequirements: ['Women in Ministry Leadership', 'Pastoral Care & Welfare', 'Liturgical Order'],
    description: 'Leader of the female fold, championing women fellowship, spiritual growth, and parish welfare.',
    levyBreakdown: {
      branchLevy: 9000,
      districtLevy: 9000,
      provincialLevy: 12000,
      nationalFee: 15000,
      total: 45000,
    },
  },
  {
    id: 'rank_dorcas',
    name: 'Dorcas',
    shortCode: 'DCS',
    orderLevel: 3,
    genderEligibility: 'female',
    prerequisiteRankId: 'rank_lady_leader',
    prerequisiteRankName: 'Lady Leader',
    minimumYearsInCurrentRank: 3,
    robingCategory: 'White_Gold',
    liturgicalColor: 'White',
    badgeColor: 'bg-amber-100 text-amber-900 border-amber-300 dark:bg-amber-950/60 dark:text-amber-200',
    theologicalRequirements: ['Benevolence Ministry & Almsgiving', 'Widows & Orphans Care', 'Sanctuary Vestment Preparation'],
    description: 'Holy Order of Dorcas, custodians of charity, benevolence, and sacred sanctuary garments.',
    levyBreakdown: {
      branchLevy: 10000,
      districtLevy: 10000,
      provincialLevy: 15000,
      nationalFee: 20000,
      total: 55000,
    },
  },
  {
    id: 'rank_deborah',
    name: 'Deborah',
    shortCode: 'DBH',
    orderLevel: 4,
    genderEligibility: 'female',
    prerequisiteRankId: 'rank_dorcas',
    prerequisiteRankName: 'Dorcas',
    minimumYearsInCurrentRank: 3,
    robingCategory: 'White_Gold',
    liturgicalColor: 'White',
    badgeColor: 'bg-amber-100 text-amber-900 border-amber-300 dark:bg-amber-950/60 dark:text-amber-200',
    theologicalRequirements: ['Spiritual Warfare & Intercession', 'Judicial Wisdom & Family Counseling', 'Prophetic Song Ministry'],
    description: 'Holy Order of Deborah, counselors, spiritual judges, and warriors of prayer in Israel.',
    levyBreakdown: {
      branchLevy: 12000,
      districtLevy: 12000,
      provincialLevy: 18000,
      nationalFee: 23000,
      total: 65000,
    },
  },
  {
    id: 'rank_mary',
    name: 'Mary',
    shortCode: 'MRY',
    orderLevel: 5,
    genderEligibility: 'female',
    prerequisiteRankId: 'rank_deborah',
    prerequisiteRankName: 'Deborah',
    minimumYearsInCurrentRank: 3,
    robingCategory: 'White_Gold',
    liturgicalColor: 'White',
    badgeColor: 'bg-purple-100 text-purple-900 border-purple-300 dark:bg-purple-950/60 dark:text-purple-200 font-bold',
    theologicalRequirements: ['Theology of the Incarnation & Humility', 'Maternal Intercession', 'Sanctuary Sanctification'],
    description: 'Holy Order of Mary, emblems of purity, devotion, and steadfast altar intercession.',
    levyBreakdown: {
      branchLevy: 15000,
      districtLevy: 15000,
      provincialLevy: 20000,
      nationalFee: 30000,
      total: 80000,
    },
  },
  {
    id: 'rank_prophetess',
    name: 'Prophetess',
    shortCode: 'PRP',
    orderLevel: 6,
    genderEligibility: 'female',
    prerequisiteRankId: 'rank_mary',
    prerequisiteRankName: 'Mary',
    minimumYearsInCurrentRank: 4,
    robingCategory: 'Purple_Gold',
    liturgicalColor: 'Purple',
    badgeColor: 'bg-purple-100 text-purple-900 border-purple-400 dark:bg-purple-950/60 dark:text-purple-200 font-bold',
    theologicalRequirements: ['Biblical Pneumatology & Prophecy', 'Spiritual Discernment & Visions', 'Order of Holy Mount Vigils'],
    description: 'Holy Order of Prophetess, prophetic oracles, spiritual seers, and prayer vigil leaders.',
    levyBreakdown: {
      branchLevy: 18000,
      districtLevy: 18000,
      provincialLevy: 24000,
      nationalFee: 35000,
      total: 95000,
    },
  },
  {
    id: 'rank_mother_in_israel',
    name: 'Mother in Israel',
    shortCode: 'MII',
    orderLevel: 7,
    genderEligibility: 'female',
    prerequisiteRankId: 'rank_prophetess',
    prerequisiteRankName: 'Prophetess',
    minimumYearsInCurrentRank: 4,
    robingCategory: 'Purple_Gold',
    liturgicalColor: 'Purple',
    badgeColor: 'bg-purple-200 text-purple-950 border-purple-400 dark:bg-purple-900/80 dark:text-purple-100 font-bold',
    theologicalRequirements: ['Matriarchal Ecclesiology', 'Matron Counseling & Family Mediation', 'Sanctuary Protocol Governance'],
    description: 'Matriarch of the Holy Order, advisor on family, counseling, and district prayer altars.',
    levyBreakdown: {
      branchLevy: 20000,
      districtLevy: 20000,
      provincialLevy: 30000,
      nationalFee: 45000,
      total: 115000,
    },
  },
  {
    id: 'rank_senior_mother_in_israel',
    name: 'Snr. Mother in Israel',
    shortCode: 'SMI',
    orderLevel: 8,
    genderEligibility: 'female',
    prerequisiteRankId: 'rank_mother_in_israel',
    prerequisiteRankName: 'Mother in Israel',
    minimumYearsInCurrentRank: 4,
    robingCategory: 'Red_Gold',
    liturgicalColor: 'Crimson',
    badgeColor: 'bg-rose-100 text-rose-900 border-rose-400 dark:bg-rose-950/60 dark:text-rose-200 font-bold',
    theologicalRequirements: ['Provincial Matron Synod Leadership', 'Holy Mount Sacred Ordinances', 'Advanced Ecclesiastical Ethics'],
    description: 'Senior provincial matriarch, custodian of spiritual counsel and provincial women leadership.',
    levyBreakdown: {
      branchLevy: 25000,
      districtLevy: 25000,
      provincialLevy: 35000,
      nationalFee: 55000,
      total: 140000,
    },
  },
  {
    id: 'rank_special_senior_mother_in_israel',
    name: 'Sp. Snr. Mother in Israel',
    shortCode: 'SSMI',
    orderLevel: 9,
    genderEligibility: 'female',
    prerequisiteRankId: 'rank_senior_mother_in_israel',
    prerequisiteRankName: 'Snr. Mother in Israel',
    minimumYearsInCurrentRank: 5,
    robingCategory: 'Red_Gold',
    liturgicalColor: 'Crimson',
    badgeColor: 'bg-rose-200 text-rose-950 border-rose-500 dark:bg-rose-900/90 dark:text-rose-100 font-extrabold shadow-sm',
    theologicalRequirements: ['Supreme Matriarch Council Fellowship', 'Holy Synod Advisory Board Conclave', 'Apex Philanthropic Governance'],
    description: 'Highest matriarchal dignity, apex council member on holy ordinances, advisory to the Supreme Head.',
    levyBreakdown: {
      branchLevy: 30000,
      districtLevy: 30000,
      provincialLevy: 45000,
      nationalFee: 65000,
      total: 170000,
    },
  },
];

export const ESOCS_PROVINCES = [
  'Lagos Central Province',
  'Lagos Western Province',
  'Lagos Eastern Province',
  'Northern Province (Abuja / Kaduna / Kano)',
  'Eastern Province (Enugu / Aba / Owerri)',
  'Niger Delta Province (Port Harcourt / Bayelsa)',
  'Edo / Delta Province',
  'Western Province (Ibadan / Ondo / Osun)',
  'United Kingdom & Europe Diocese',
  'North America Diocese (USA & Canada)',
  'Rest of Africa & Diaspora',
];

export const VETTING_TIERS = [
  { id: 'branch', label: 'Branch / Parish Level', description: 'Parish Priest verification of baptism, tithing, marriage & local church attendance' },
  { id: 'district', label: 'District Level', description: 'District Overseer vetting & quota approval' },
  { id: 'province', label: 'Provincial Level', description: 'Provincial Secretariat verification & zonal credentials review' },
  { id: 'cmc', label: 'CMC Level (National Screening)', description: 'Church Management Council doctrinal examination & oral interview' },
  { id: 'national', label: 'National / Holy Synod', description: 'Supreme ratification by His Most Eminence & Advisory Board of Elders' },
];

export const PASSING_EXAM_CUTOFF = 70;
export const PASSING_INTERVIEW_CUTOFF = 75;
export const MIN_ATTENDANCE_PERCENTAGE = 85;
