'use client';

import React, { useState } from 'react';
import { useAuth } from '@/context/AuthContext';
import { Button } from '@/components/ui/Button';
import { EsocsLogo } from '@/components/ui/EsocsLogo';
import {
  X,
  ShieldCheck,
  Smartphone,
  AlertCircle,
  ArrowRight,
  RefreshCw,
} from 'lucide-react';

export function TwoFactorModal() {
  const { twoFactorPending, verifyTwoFactor, cancelTwoFactor, isLoading } = useAuth();
  const [otp, setOtp] = useState('');
  const [rememberDevice, setRememberDevice] = useState(true);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  if (!twoFactorPending) return null;

  const handleVerify = async (e: React.FormEvent) => {
    e.preventDefault();
    setErrorMsg(null);

    if (!otp.trim() || otp.length < 6) {
      setErrorMsg('Please enter your 6-digit canonical authentication code.');
      return;
    }

    try {
      await verifyTwoFactor(otp.trim(), rememberDevice);
    } catch (err: any) {
      setErrorMsg(err.message || 'Invalid authentication code. Please try again.');
    }
  };

  const handleDemoBypass = () => {
    setOtp('948210');
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 bg-slate-950/80 backdrop-blur-sm overflow-y-auto">
      <div className="relative w-full max-w-md bg-white dark:bg-slate-900 rounded-3xl border border-slate-200 dark:border-slate-800 shadow-premium overflow-hidden transition-all text-slate-900 dark:text-slate-100">
        {/* Modal Header */}
        <div className="flex items-center justify-between p-5 border-b border-slate-100 dark:border-slate-800 bg-slate-50/70 dark:bg-slate-900/90">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-xl bg-gold-500/20 text-gold-600 dark:text-gold-400">
              <ShieldCheck className="w-5 h-5" />
            </div>
            <div>
              <h3 className="font-serif text-base sm:text-lg font-bold text-church-950 dark:text-white">
                Two-Factor Security (2FA)
              </h3>
              <p className="text-[11px] text-slate-500 dark:text-slate-400">
                Apostolic multi-factor credential verification
              </p>
            </div>
          </div>
          <button
            onClick={cancelTwoFactor}
            className="p-1.5 rounded-full hover:bg-slate-200 dark:hover:bg-slate-800 text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Body */}
        <form onSubmit={handleVerify} className="p-5 sm:p-6 text-xs space-y-4">
          {errorMsg && (
            <div className="p-3 bg-rose-50 dark:bg-rose-950/40 border border-rose-200 dark:border-rose-900 text-rose-700 dark:text-rose-300 rounded-xl flex items-center gap-2">
              <AlertCircle className="w-4 h-4 shrink-0" />
              <span>{errorMsg}</span>
            </div>
          )}

          <div className="text-center space-y-2 py-1">
            <div className="w-12 h-12 mx-auto rounded-2xl bg-church-50 dark:bg-church-900/50 text-church-700 dark:text-gold-400 flex items-center justify-center">
              <Smartphone className="w-6 h-6" />
            </div>
            <p className="text-slate-600 dark:text-slate-400 leading-relaxed max-w-xs mx-auto text-xs">
              Enter the 6-digit authentication token generated by your authenticator app or dispatched to your church email.
            </p>
          </div>

          <div>
            <label className="block text-center font-semibold text-slate-700 dark:text-slate-300 mb-2">
              6-Digit Canonical Token
            </label>
            <input
              type="text"
              required
              maxLength={6}
              autoFocus
              value={otp}
              onChange={(e) => setOtp(e.target.value)}
              placeholder="000000"
              className="w-full text-center tracking-[0.5em] font-mono text-2xl py-3 bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 rounded-2xl focus:ring-2 focus:ring-church-500 focus:outline-none"
            />
          </div>

          {/* Quick Demo Helper */}
          <div className="flex items-center justify-between text-[11px] text-slate-500">
            <button
              type="button"
              onClick={handleDemoBypass}
              className="text-gold-700 dark:text-gold-400 hover:underline flex items-center gap-1 font-medium"
            >
              <RefreshCw className="w-3 h-3" /> Auto-fill Demo Token (948210)
            </button>
            <span>Time remaining: 5:00</span>
          </div>

          {/* Remember Device */}
          <label className="flex items-center gap-2 pt-1 cursor-pointer select-none">
            <input
              type="checkbox"
              checked={rememberDevice}
              onChange={(e) => setRememberDevice(e.target.checked)}
              className="w-4 h-4 rounded text-church-600 focus:ring-church-500 border-slate-300 dark:border-slate-600"
            />
            <span className="text-[11px] text-slate-600 dark:text-slate-300">
              Trust and remember this ecclesiastical terminal for 30 days
            </span>
          </label>

          {/* Actions */}
          <div className="pt-3 flex items-center justify-between gap-3">
            <Button variant="outline" size="md" type="button" onClick={cancelTwoFactor}>
              Cancel Sign In
            </Button>
            <Button
              variant="primary"
              size="md"
              type="submit"
              loading={isLoading}
              icon={<ArrowRight className="w-4 h-4" />}
            >
              Verify & Enter Portal
            </Button>
          </div>
        </form>
      </div>
    </div>
  );
}

